name: Apply Branch Protection Rules

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'List of repositories (comma-separated, e.g., "repo1,repo2,repo3")'
        required: false
        type: string
      prefix:
        description: 'Repository prefix to filter by (e.g., "oof-latax-")'
        required: false
        default: 'oof-latax-'
        type: string
      organization:
        description: 'GitHub organization name'
        required: true
        default: 'CityOfLosAngeles'
        type: string

jobs:
  # Use the reusable base workflow to get repository information
  setup:
    uses: ./.github/workflows/base-utils-workflow.yml
    with:
      repositories: ${{ github.event.inputs.repositories }}
      prefix: ${{ github.event.inputs.prefix }}
      organization: ${{ github.event.inputs.organization }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  
  # Apply branch protection rules to repositories
  apply-branch-rules:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install @octokit/rest
      
      - name: Apply branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          ORGANIZATION: ${{ github.event.inputs.organization }}
          REPOSITORIES: ${{ needs.setup.outputs.repos_json }}
        run: node .github/scripts/apply-branch-rules.js